import { Router } from "express";
import { db } from "../db";
import { legalArticles, legalArticleTags } from "../schema";
import { eq } from "drizzle-orm";
import crypto from "crypto";

const router = Router();
const INTERNAL_KEY = process.env.INTERNAL_INGEST_KEY!;

/* ---------------------------------------------------------
   POST /internal/legal/legal-articles/ingest
--------------------------------------------------------- */
router.post("/legal-articles/ingest", async (req, res) => {
  try {
    const key = req.headers["x-internal-key"];
    if (key !== INTERNAL_KEY) {
      return res.status(401).json({ error: "unauthorized" });
    }

    const {
      source,
      title,
      raw_content,
      link,
      published_at,
      tags = [],
    } = req.body;

    if (!raw_content || !source) {
      return res.status(400).json({ error: "missing_fields" });
    }

    // Anti doublon sur texte brut
    const exists = await db
      .select()
      .from(legalArticles)
      .where(eq(legalArticles.rawContent, raw_content));

    if (exists.length > 0) {
      return res.json({
        status: "duplicate_skipped",
        articleId: exists[0].id,
      });
    }

    const id = crypto.randomUUID();

    const [row] = await db
      .insert(legalArticles)
      .values({
        id,
        title: title || null,
        rawContent: raw_content,
        source,
        sourceUrl: link || null,
        autoGenerated: true,
        status: "INGESTED",
        publishedAt: published_at ? new Date(published_at) : null,
        createdAt: new Date(),
      })
      .returning();

    // TAGS éventuels
    if (tags && Array.isArray(tags) && tags.length > 0) {
      await db.insert(legalArticleTags).values(
        tags.map((t: string) => ({
          id: crypto.randomUUID(),
          articleId: id,
          tag: t,
        }))
      );
    }

    return res.json({
      status: "ingested",
      articleId: row.id,
    });
  } catch (err) {
    console.error("INGEST ERROR:", err);
    return res.status(500).json({ error: "failed" });
  }
});

export default router;
