import { Router } from "express";
import { db } from "../db";
import { legalArticles, legalArticleTags, users } from "../schema";
import { eq, inArray, desc } from "drizzle-orm";
import { requireAuth } from "../middleware/requireAuth";
import crypto from "crypto";
import { z } from "zod";
import { sql } from "drizzle-orm/sql"; // IMPORTANT : version qui marche chez toi

const router = Router();

/* ---------------------------------------------------------
   ZOD VALIDATION
--------------------------------------------------------- */
const createManualSchema = z.object({
  title: z.string(),
  body: z.string(),
  tags: z.array(z.string()).optional(),
});

const updateSchema = z.object({
  title: z.string().optional(),
  body: z.string().optional(),
  tags: z.array(z.string()).optional(),
});

/* ---------------------------------------------------------
   SUPER ADMIN CHECK
--------------------------------------------------------- */
async function isSuperAdmin(userId: string): Promise<boolean> {
  const result = await db.select().from(users).where(eq(users.id, userId));
  return result.length > 0 && result[0].role === "SUPER_ADMIN";
}

/* ---------------------------------------------------------
   POST /legal-articles
   Création manuelle (SUPER ADMIN)
--------------------------------------------------------- */
router.post("/", requireAuth, async (req, res) => {
  try {
    const userId = (req as any).userId;

    if (!(await isSuperAdmin(userId))) {
      return res.status(403).json({ error: "NOT_ALLOWED" });
    }

    const parsed = createManualSchema.safeParse(req.body);
    if (!parsed.success) {
      return res.status(400).json({
        error: "INVALID_DATA",
        details: parsed.error.flatten(),
      });
    }

    const { title, body, tags = [] } = parsed.data;
    const id = crypto.randomUUID();

    const [article] = await db
      .insert(legalArticles)
      .values({
        id,
        title,
        body,
        rawContent: body,
        source: "manual",
        sourceUrl: null,
        publishedAt: null,
        autoGenerated: false,
        aiSummary: null,
        humanSummary: null,
        status: "READY",
        createdAt: new Date(),
      })
      .returning();

    if (tags.length > 0) {
      await db.insert(legalArticleTags).values(
        tags.map((t) => ({
          id: crypto.randomUUID(),
          articleId: id,
          tag: t,
        }))
      );
    }

    res.json({
      ...article,
      tags,
    });
  } catch (err) {
    console.error("CREATE LEGAL ARTICLE ERROR:", err);
    res.status(500).json({ error: "Create failed" });
  }
});

/* ---------------------------------------------------------
   GET /legal-articles
   LISTE + TAG FILTER + PAGINATION
--------------------------------------------------------- */
router.get("/", async (req, res) => {
  try {
    let page = Number(req.query.page ?? "1");
    let pageSize = Number(req.query.pageSize ?? "20");
    const tagFilter = (req.query.tag as string | undefined) || null;

    if (page < 1) page = 1;
    if (pageSize < 1) pageSize = 20;
    if (pageSize > 100) pageSize = 100;

    const offset = (page - 1) * pageSize;
    let articles;

    if (tagFilter) {
      const tagRows = await db
        .select()
        .from(legalArticleTags)
        .where(eq(legalArticleTags.tag, tagFilter));

      const ids = tagRows.map((t) => t.articleId);
      if (ids.length === 0) return res.json([]);

      articles = await db
        .select()
        .from(legalArticles)
        .where(inArray(legalArticles.id, ids))
        .orderBy(desc(legalArticles.createdAt))
        .limit(pageSize)
        .offset(offset);
    } else {
      articles = await db
        .select()
        .from(legalArticles)
        .orderBy(desc(legalArticles.createdAt))
        .limit(pageSize)
        .offset(offset);
    }

    const withTags = await Promise.all(
      articles.map(async (a) => {
        const tagRows = await db
          .select()
          .from(legalArticleTags)
          .where(eq(legalArticleTags.articleId, a.id));
        return { ...a, tags: tagRows.map((t) => t.tag) };
      })
    );

    res.json(withTags);
  } catch (err) {
    console.error("LIST LEGAL ARTICLES ERROR:", err);
    res.status(500).json({ error: "Server error" });
  }
});

/* ---------------------------------------------------------
   GET /legal-articles/search
   FULL TEXT SEARCH (public)
   !!! IMPORTANT : AVANT /:id
--------------------------------------------------------- */
router.get("/search", async (req, res) => {
  try {
    const q = (req.query.q as string | undefined)?.trim() || "";
    const page = parseInt((req.query.page as string) || "1", 10);
    const pageSize = parseInt((req.query.pageSize as string) || "10", 10);

    if (!q) return res.status(400).json({ error: "MISSING_QUERY" });

    const offset = (page - 1) * pageSize;
    const like = `%${q}%`;

    const articles = await db
      .select()
      .from(legalArticles)
      .where(
        sql`${legalArticles.title} ILIKE ${like} OR ${legalArticles.body} ILIKE ${like}`
      )
      .orderBy(desc(legalArticles.createdAt))
      .limit(pageSize)
      .offset(offset);

    const withTags = await Promise.all(
      articles.map(async (a) => {
        const tags = await db
          .select()
          .from(legalArticleTags)
          .where(eq(legalArticleTags.articleId, a.id));

        return { ...a, tags: tags.map((t) => t.tag) };
      })
    );

    res.json({
      page,
      pageSize,
      items: withTags,
    });
  } catch (err) {
    console.error("SEARCH ERROR:", err);
    res.status(500).json({ error: "Server error" });
  }
});

/* ---------------------------------------------------------
   GET /legal-articles/latest
   DERNIERS ARTICLES (public)
--------------------------------------------------------- */
router.get("/latest", async (req, res) => {
  try {
    const limit = parseInt((req.query.limit as string) || "5", 10);

    const articles = await db
      .select()
      .from(legalArticles)
      .orderBy(desc(legalArticles.createdAt))
      .limit(limit);

    const withTags = await Promise.all(
      articles.map(async (a) => {
        const tags = await db
          .select()
          .from(legalArticleTags)
          .where(eq(legalArticleTags.articleId, a.id));

        return { ...a, tags: tags.map((t) => t.tag) };
      })
    );

    res.json(withTags);
  } catch (err) {
    console.error("LATEST ERROR:", err);
    res.status(500).json({ error: "Server error" });
  }
});

/* ---------------------------------------------------------
   GET /legal-articles/ai-status
   PIPELINE IA (Super Admin)
--------------------------------------------------------- */
router.get("/ai-status", requireAuth, async (req, res) => {
  try {
    const userId = (req as any).userId;

    if (!(await isSuperAdmin(userId))) {
      return res.status(403).json({ error: "NOT_ALLOWED" });
    }

    const rows = await db.select().from(legalArticles);

    const byStatus: Record<string, number> = {};
    for (const r of rows) {
      const status = (r as any).status || "UNKNOWN";
      byStatus[status] = (byStatus[status] || 0) + 1;
    }

    res.json({
      total: rows.length,
      byStatus,
    });
  } catch (err) {
    console.error("AI STATUS ERROR:", err);
    res.status(500).json({ error: "Server error" });
  }
});

/* ---------------------------------------------------------
   GET /legal-articles/:id
   DETAILS (public)
   !!! PLACÉ À LA FIN
--------------------------------------------------------- */
router.get("/:id", async (req, res) => {
  try {
    const { id } = req.params;

    const [article] = await db
      .select()
      .from(legalArticles)
      .where(eq(legalArticles.id, id));

    if (!article) return res.status(404).json({ error: "NOT_FOUND" });

    const tags = await db
      .select()
      .from(legalArticleTags)
      .where(eq(legalArticleTags.articleId, id));

    res.json({ ...article, tags: tags.map((t) => t.tag) });
  } catch (err) {
    console.error("GET ARTICLE ERROR:", err);
    res.status(500).json({ error: "Server error" });
  }
});

/* ---------------------------------------------------------
   PATCH /legal-articles/:id
--------------------------------------------------------- */
router.patch("/:id", requireAuth, async (req, res) => {
  try {
    const userId = (req as any).userId;
    const { id } = req.params;

    if (!(await isSuperAdmin(userId))) {
      return res.status(403).json({ error: "NOT_ALLOWED" });
    }

    const parsed = updateSchema.safeParse(req.body);
    if (!parsed.success) {
      return res.status(400).json({
        error: "INVALID_DATA",
        details: parsed.error.flatten(),
      });
    }

    const { title, body, tags } = parsed.data;

    const updateValues: any = {};
    if (title) updateValues.title = title;
    if (body) {
      updateValues.body = body;
      updateValues.rawContent = body;
    }

    const [updated] = await db
      .update(legalArticles)
      .set(updateValues)
      .where(eq(legalArticles.id, id))
      .returning();

    if (!updated) return res.status(404).json({ error: "NOT_FOUND" });

    if (tags) {
      await db
        .delete(legalArticleTags)
        .where(eq(legalArticleTags.articleId, id));

      if (tags.length > 0) {
        await db.insert(legalArticleTags).values(
          tags.map((t) => ({
            id: crypto.randomUUID(),
            articleId: id,
            tag: t,
          }))
        );
      }
    }

    res.json(updated);
  } catch (err) {
    console.error("PATCH ERROR:", err);
    res.status(500).json({ error: "Update failed" });
  }
});

/* ---------------------------------------------------------
   DELETE /legal-articles/:id
--------------------------------------------------------- */
router.delete("/:id", requireAuth, async (req, res) => {
  try {
    const userId = (req as any).userId;
    const { id } = req.params;

    if (!(await isSuperAdmin(userId))) {
      return res.status(403).json({ error: "NOT_ALLOWED" });
    }

    await db
      .delete(legalArticleTags)
      .where(eq(legalArticleTags.articleId, id));

    await db.delete(legalArticles).where(eq(legalArticles.id, id));

    res.json({ message: "Deleted" });
  } catch (err) {
    console.error("DELETE ERROR:", err);
    res.status(500).json({ error: "Delete failed" });
  }
});

export default router;
